bitrise config ++

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,8 +3,6 @@ format_version: '4'
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: react-native
 trigger_map:
-- push_branch: "*"
-  workflow: android
 - pull_request_source_branch: "*"
   workflow: android
 workflows:
@@ -12,41 +10,72 @@ workflows:
     steps:
     - activate-ssh-key@3.1.1:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@3.5.1: {}
+    - git-clone: {}
+    - slack@2.6.3:
+        inputs:
+        - message: Building... $GIT_CLONE_COMMIT_MESSAGE_SUBJECT
+        - webhook_url: https://hooks.slack.com/services/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
+    - fastlane-match@0.1.0:
+        inputs:
+        - decrypt_password: "$MATCH_PASSWORD"
+        - app_id: "$IOS_APP_ID"
+        - git_url: https://github.com/bennytac/ios-certs
+    - script@1.1.5:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            echo "Preparing .env"
+            cp env.dev .env
     - install-react-native@0.9.1: {}
     - npm@0.9.0:
         inputs:
         - command: install
-    - install-missing-android-tools@2.0.1: {}
+    - install-missing-android-tools: {}
     - file-downloader@0.9.1:
         inputs:
         - source: "$BITRISEIO_ANDROID_DEV_KEYSTORE_URL"
         - destination: "$BITRISE_SOURCE_DIR/android/keystores/goodsh-dev.keystore"
-    - gradle-runner@1.7.6:
+    - gradle-runner@1.8.0:
         inputs:
         - gradle_file: "$GRADLE_BUILD_FILE_PATH"
         - gradle_task: assembleDev
+        - apk_file_include_filter: "*dev.apk"
         - gradlew_path: "$GRADLEW_PATH"
     - certificate-and-profile-installer@1.9.2: {}
     - recreate-user-schemes@1.0.2:
         inputs:
         - project_path: "$BITRISE_PROJECT_PATH"
-    - xcode-archive@2.1.1:
+    - cocoapods-install@1.7.2: {}
+    - xcode-archive:
         inputs:
-#        - project_path: "$BITRISE_PROJECT_PATH"
         - scheme: "$BITRISE_SCHEME"
-        - configuration: Debug
-    - hockeyapp-deploy-android@1.1.1:
+        - configuration: Release
+        - project_path: "$BITRISE_WORKSPACE_PATH"
+        - output_tool: xcodebuild
+    - hockeyapp-deploy-android:
         inputs:
         - app_id: 9413859c01db4f2cbb918da583156db2
         - api_token: 371fb124534f4777934cd8101157d47a
         - notify: '0'
+        - notes: "$GIT_CLONE_COMMIT_MESSAGE_SUBJECT"
     - hockeyapp-deploy@2.4.2:
         inputs:
         - api_token: f191e719336d431aa8e3210f64e44052
         - app_id: '0718789d9866499cbc827f68e1627a17'
         - notify: '0'
-    - deploy-to-bitrise-io@1.3.6: {}
+        - notes: "$GIT_CLONE_COMMIT_MESSAGE_SUBJECT"
+    - deploy-to-bitrise-io:
+        inputs:
+        - notify_user_groups: everyone
+    - slack@2.6.3:
+        inputs:
+        - message: 'Build and deployed: $GIT_CLONE_COMMIT_MESSAGE_SUBJECT'
+        - webhook_url: https://hooks.slack.com/services/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
   ios:
     steps:
     - activate-ssh-key@3.1.1:
@@ -107,3 +136,7 @@ app:
   - opts:
       is_expand: false
     BITRISE_SCHEME: goodshmob
+  - BITRISE_WORKSPACE_PATH: ios/goodshmob.xcworkspace
+  - IOS_APP_ID: it.goodsh.mob.dev
+    opts:
+      is_expand: false
